markdown: kramdown
highlighter: rouge
permalink: /:categories/:title.html 

page_excerpts: true
excerpt_separator: "<!-- more -->"

# Todos los autores tienen links personales
authors:
- name: Narinas
  github: Narinas
  email: narinas@narinas.xyz
  
# Información del blog
name: "MOOLabs"
baseurl: "/lab-blog"
url: "moo-labs.github.io"
domain: ""

# Mapa de sitio
all_categories: [
  ["Posts", "/index.html"],
  ["Proyectos", "/projects.html"],
  ["Acerca de", "/about.html"]
]

# 
paginate: 10 
paginate_path: "index_:num"

index_layout: "index.html"

plugins: [jekyll-paginate]

copyright: []